# Use Node base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install deps
COPY package*.json ./
RUN npm install --production

# Copy rest of the code
COPY . .

# Expose the app port
EXPOSE 3000

# Start the server
CMD ["npm", "start"]
