import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ResponsiveAppBar from "@/components/navbar";
import Footer from "@/components/footer";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import ThemeRegistry from "./ThemeRegistry";

export const metadata: Metadata = {
  title: "Anonymous Thoughts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AppRouterCacheProvider>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              minHeight: "100vh",
            }}
          >
            {" "}
            <ThemeRegistry>
              {children}
              <Footer />
            </ThemeRegistry>
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
